source 'https://github.com/CocoaPods/Specs.git'

target 'LSDCoreDataHelpers', :exclusive => true do
  pod "LSDCoreDataHelpers", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "LSDCoreDataHelpers", :path => "../"

  
end
